version: "3"

x-uffizzi:
    ingress:
        service: online-go
        port: 8080

services:
    online-go:
        image: "${ONLINE_GO_IMAGE}"
        environment:
            #OGS_BACKEND: PRODUCTION
            OGS_BACKEND: BETA
        # entrypoint:
        # - "sh"
        # command:
        # - "-c"
        # - "npm run dev"
        deploy:
            resources:
                limits:
                    memory: 4000M
