name: Trigger E2E Tests

#on:
#  push:
#    branches:
#      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    # Only run on the original repo, not forks
    if: github.repository == 'online-go/online-go.com'

    steps:
      - name: Trigger E2E tests in ogs repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.E2E_DISPATCH_TOKEN }}
          repository: online-go/ogs
          event-type: trigger-e2e-tests
          client-payload: '{"triggered_by": "ogs-ui", "sha": "${{ github.sha }}"}'
